namespace MiniBowser
{
    public class Bookmark
    {
        // Instance Variables
        // Auto generated by the properties

        // Accessors
        public string Name
        { get; set; }

        public string Url
        { get; set; }

        // Constructor
        public Bookmark(string name, string url)
        {
            Name = name;
            Url = url;
        }
    }
}
