using System.Collections.Generic;

namespace MiniBowser
{
    public class History
    {
        // Class Variables
        private static int StackSize = 30;
        private static int ListSize = 30;

        // Instance Variables
        // Autogenerated by the properties

        // Accessors
        public List<string> UrlList
        { get; private set; }

        public Stack<string> PreviousSites
        { get; private set; }

        public Stack<string> NextSites
        { get; private set; }

        // Constructors
        public History(string homePageUrl)
        {
            UrlList = new List<string>(ListSize);
            UrlList.Add(homePageUrl);
            PreviousSites = new Stack<string>(StackSize);
            NextSites = new Stack<string>(StackSize);
        }

        public History()
        {
            UrlList = new List<string>(ListSize);
            UrlList.Add("https://www.google.com/");
            PreviousSites = new Stack<string>(StackSize);
            NextSites = new Stack<string>(StackSize);
        }

        // Methods
        public void AddSiteToList(string url)
        {
            if (UrlList.Count >= ListSize)
            {
                UrlList.RemoveAt(0);
            }

            UrlList.Add(url);
        }

        public string GetCurrentSite()
        {
            return UrlList[UrlList.Count-1];
        }

        public void AddNewSite(string url)
        {
            AddSiteToList(url);
            PreviousSites.Push(url);
        }

        public string ReturnPreviousSite(string currentSite)
        {
            string previousSite = PreviousSites.Pop();
            NextSites.Push(currentSite);
            AddSiteToList(currentSite);
            return previousSite;
        }

        public string ReturnNextSite(string currentSite)
        {
            string nextSite = NextSites.Pop();
            PreviousSites.Push(currentSite);
            AddSiteToList(currentSite);
            return nextSite;
        }
    }
}
