using System;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace MiniBowser
{
    public class MiniBowser
    {
        // Class variables
        public readonly HttpHandler httpHandler = new HttpHandler();

        // Instance Variables
        // Autogenerated by properties

        // Accessors
        public string CurrentSite
        { get; set; }

        public string Homepage
        { get; set; }

        public List<Bookmark> BookmarkList
        { get; set; }

        public History History
        { get; private set; }

        public Serializer Serializer
        { get; private set; }


        // Constructor
        public MiniBowser()
        {
            //TODO! Extract the behavior and reuse it
            Serializer = new Serializer();
            // Load history if existing
            if (File.Exists(Serializer.pathHistory))
            {
                History = Serializer.DeserializeAndLoadHistory();
            }
            else
            {
                History = new History();
                History.UrlList = new List<string>() { "", "", "", "", "", "", "", "" };
            }
            // Load bookmarks if existing
            if (File.Exists(Serializer.pathBookmarks))
            {
                BookmarkList = Serializer.DeserializeAndLoadBookmarks();
            }
            else
            {
                BookmarkList = new List<Bookmark>() { new Bookmark("", ""), new Bookmark("", ""),
                                                      new Bookmark("", ""), new Bookmark("", ""),
                                                      new Bookmark("", ""), new Bookmark("", ""),
                                                      new Bookmark("", ""), new Bookmark("", "") };
            }

            // Load Homepage if existing
            if (File.Exists(Serializer.pathHomepage))
            {
                Homepage = Serializer.DeserializeAndLoadHomepage();
            }
            else
            {
                Homepage = "https://www.google.com/";
            }
        }

        // Methods
        public void AddBookmark(Bookmark newBookmark)
        {
            BookmarkList.Add(newBookmark);
        }

        public void RemoveBookmark(Bookmark bookmark)
        {
            if (BookmarkList.Contains(bookmark))
            {
                BookmarkList.Remove(bookmark);
            }
        }

        public void Store()
        {
            Serializer.SerializeAndStoreBrowser(this);
        }

        public string RequestResult(string url)
        {
            HttpData requestRes = new HttpData();
            Task<HttpData> taskRes = httpHandler.RequestResponse(url);
            requestRes = taskRes.Result;
            // display html content(tostring)
            return requestRes.ToString();
        }
    }
}
