
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action previousButton;

	private global::Gtk.Action nextButton;

	private global::Gtk.Action reloadButton;

	private global::Gtk.Action searchButton;

	private global::Gtk.Action bookmarksButton;

	private global::Gtk.Action historyButton;

	private global::Gtk.Action homeButton;

	private global::Gtk.Action setHomeButton;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Toolbar toolbar3;

	private global::Gtk.Entry urlEntry;

	private global::Gtk.Toolbar toolbar5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView htmlTextView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.previousButton = new global::Gtk.Action("previousButton", global::Mono.Unix.Catalog.GetString("Previous"), null, "gtk-undo");
		this.previousButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Previous");
		w1.Add(this.previousButton, null);
		this.nextButton = new global::Gtk.Action("nextButton", global::Mono.Unix.Catalog.GetString("Next"), null, "gtk-redo");
		this.nextButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Next");
		w1.Add(this.nextButton, null);
		this.reloadButton = new global::Gtk.Action("reloadButton", global::Mono.Unix.Catalog.GetString("Reload"), null, "gtk-refresh");
		this.reloadButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Reload");
		w1.Add(this.reloadButton, null);
		this.searchButton = new global::Gtk.Action("searchButton", global::Mono.Unix.Catalog.GetString("Search"), null, "gtk-find");
		this.searchButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Search");
		w1.Add(this.searchButton, null);
		this.bookmarksButton = new global::Gtk.Action("bookmarksButton", global::Mono.Unix.Catalog.GetString("Bookmarks"), null, "gtk-open");
		this.bookmarksButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Bookmarks");
		w1.Add(this.bookmarksButton, null);
		this.historyButton = new global::Gtk.Action("historyButton", global::Mono.Unix.Catalog.GetString("History"), null, "gtk-copy");
		this.historyButton.ShortLabel = global::Mono.Unix.Catalog.GetString("History");
		w1.Add(this.historyButton, null);
		this.homeButton = new global::Gtk.Action("homeButton", global::Mono.Unix.Catalog.GetString("Home"), null, "gtk-home");
		this.homeButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Home");
		w1.Add(this.homeButton, null);
		this.setHomeButton = new global::Gtk.Action("setHomeButton", global::Mono.Unix.Catalog.GetString("Set Home"), null, "gtk-execute");
		this.setHomeButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Set Home");
		w1.Add(this.setHomeButton, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 600;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar3'><toolitem name='previousButton' action='previousButton'/><toolitem name='nextButton' action='nextButton'/><toolitem name='reloadButton' action='reloadButton'/><toolitem name='homeButton' action='homeButton'/><toolitem name='setHomeButton' action='setHomeButton'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.hbox4.Add(this.toolbar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.toolbar3]));
		w2.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.urlEntry = new global::Gtk.Entry();
		this.urlEntry.CanFocus = true;
		this.urlEntry.Name = "urlEntry";
		this.urlEntry.IsEditable = true;
		this.urlEntry.InvisibleChar = '●';
		this.hbox4.Add(this.urlEntry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.urlEntry]));
		w3.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar5\'><toolitem name=\'searchButton\' action=\'searchButton\'/" +
				"><toolitem name=\'bookmarksButton\' action=\'bookmarksButton\'/><toolitem name=\'hist" +
				"oryButton\' action=\'historyButton\'/></toolbar></ui>");
		this.toolbar5 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar5")));
		this.toolbar5.Name = "toolbar5";
		this.toolbar5.ShowArrow = false;
		this.hbox4.Add(this.toolbar5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.toolbar5]));
		w4.Position = 2;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.htmlTextView = new global::Gtk.TextView();
		this.htmlTextView.CanFocus = true;
		this.htmlTextView.Name = "htmlTextView";
		this.GtkScrolledWindow.Add(this.htmlTextView);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w7.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.previousButton.Activated += new global::System.EventHandler(this.PreviousButtonClicked);
		this.nextButton.Activated += new global::System.EventHandler(this.NextButtonClicked);
		this.reloadButton.Activated += new global::System.EventHandler(this.ReloadButtonClicked);
		this.searchButton.Activated += new global::System.EventHandler(this.SearchButtonClicked);
		this.bookmarksButton.Activated += new global::System.EventHandler(this.BookmarksButtonClicked);
		this.historyButton.Activated += new global::System.EventHandler(this.HistoryButtonClicked);
		this.homeButton.Activated += new global::System.EventHandler(this.HomeButtonClicked);
		this.setHomeButton.Activated += new global::System.EventHandler(this.SetHomeButtonClicked);
	}
}
