
// This file has been generated by the GUI designer. Do not modify.
namespace MiniBowserGUI
{
	public partial class BookmarksWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action editButton;

		private global::Gtk.Action saveButton;

		private global::Gtk.Action goButton1;

		private global::Gtk.Action deleteButton1;

		private global::Gtk.Action goButton2;

		private global::Gtk.Action deleteButton2;

		private global::Gtk.Action goButton3;

		private global::Gtk.Action deleteButton3;

		private global::Gtk.Action goButton4;

		private global::Gtk.Action deleteButton4;

		private global::Gtk.Action goButton5;

		private global::Gtk.Action deleteButton5;

		private global::Gtk.Action goButton6;

		private global::Gtk.Action deleteButton6;

		private global::Gtk.Action goButton7;

		private global::Gtk.Action deleteButton7;

		private global::Gtk.Action goButton8;

		private global::Gtk.Action deleteButton8;

		private global::Gtk.VBox vbox8;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Entry nameEntry1;

		private global::Gtk.Entry urlEntry1;

		private global::Gtk.Toolbar toolbar32;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Entry nameEntry2;

		private global::Gtk.Entry urlEntry2;

		private global::Gtk.Toolbar toolbar34;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Entry nameEntry3;

		private global::Gtk.Entry urlEntry3;

		private global::Gtk.Toolbar toolbar36;

		private global::Gtk.VBox vbox11;

		private global::Gtk.HBox hbox27;

		private global::Gtk.Entry nameEntry4;

		private global::Gtk.Entry urlEntry4;

		private global::Gtk.Toolbar toolbar38;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Entry nameEntry5;

		private global::Gtk.Entry urlEntry5;

		private global::Gtk.Toolbar toolbar40;

		private global::Gtk.HBox hbox31;

		private global::Gtk.Entry nameEntry6;

		private global::Gtk.Entry urlEntry6;

		private global::Gtk.Toolbar toolbar42;

		private global::Gtk.VBox vbox13;

		private global::Gtk.HBox hbox33;

		private global::Gtk.Entry nameEntry7;

		private global::Gtk.Entry urlEntry7;

		private global::Gtk.Toolbar toolbar44;

		private global::Gtk.HBox hbox35;

		private global::Gtk.Entry nameEntry8;

		private global::Gtk.Entry urlEntry8;

		private global::Gtk.Toolbar toolbar46;

		private global::Gtk.HBox hbox37;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Toolbar toolbar30;

		private global::Gtk.HSeparator hseparator3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MiniBowserGUI.BookmarksWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.editButton = new global::Gtk.Action("editButton", global::Mono.Unix.Catalog.GetString("Edit"), null, "gtk-preferences");
			this.editButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.editButton, null);
			this.saveButton = new global::Gtk.Action("saveButton", global::Mono.Unix.Catalog.GetString("Save"), null, "gtk-save");
			this.saveButton.Sensitive = false;
			this.saveButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
			w1.Add(this.saveButton, null);
			this.goButton1 = new global::Gtk.Action("goButton1", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton1.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton1, null);
			this.deleteButton1 = new global::Gtk.Action("deleteButton1", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton1.Sensitive = false;
			this.deleteButton1.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton1, null);
			this.goButton2 = new global::Gtk.Action("goButton2", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton2.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton2, null);
			this.deleteButton2 = new global::Gtk.Action("deleteButton2", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton2.Sensitive = false;
			this.deleteButton2.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton2, null);
			this.goButton3 = new global::Gtk.Action("goButton3", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton3.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton3, null);
			this.deleteButton3 = new global::Gtk.Action("deleteButton3", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton3.Sensitive = false;
			this.deleteButton3.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton3, null);
			this.goButton4 = new global::Gtk.Action("goButton4", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton4.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton4, null);
			this.deleteButton4 = new global::Gtk.Action("deleteButton4", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton4.Sensitive = false;
			this.deleteButton4.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton4, null);
			this.goButton5 = new global::Gtk.Action("goButton5", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton5.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton5, null);
			this.deleteButton5 = new global::Gtk.Action("deleteButton5", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton5.Sensitive = false;
			this.deleteButton5.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton5, null);
			this.goButton6 = new global::Gtk.Action("goButton6", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton6.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton6, null);
			this.deleteButton6 = new global::Gtk.Action("deleteButton6", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton6.Sensitive = false;
			this.deleteButton6.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton6, null);
			this.goButton7 = new global::Gtk.Action("goButton7", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton7.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton7, null);
			this.deleteButton7 = new global::Gtk.Action("deleteButton7", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton7.Sensitive = false;
			this.deleteButton7.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton7, null);
			this.goButton8 = new global::Gtk.Action("goButton8", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton8.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton8, null);
			this.deleteButton8 = new global::Gtk.Action("deleteButton8", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-stop");
			this.deleteButton8.Sensitive = false;
			this.deleteButton8.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
			w1.Add(this.deleteButton8, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "MiniBowserGUI.BookmarksWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("BookmarksWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MiniBowserGUI.BookmarksWindow.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.nameEntry1 = new global::Gtk.Entry();
			this.nameEntry1.Sensitive = false;
			this.nameEntry1.CanFocus = true;
			this.nameEntry1.Name = "nameEntry1";
			this.nameEntry1.IsEditable = true;
			this.nameEntry1.InvisibleChar = '●';
			this.hbox21.Add(this.nameEntry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.nameEntry1]));
			w2.Position = 0;
			// Container child hbox21.Gtk.Box+BoxChild
			this.urlEntry1 = new global::Gtk.Entry();
			this.urlEntry1.Sensitive = false;
			this.urlEntry1.CanFocus = true;
			this.urlEntry1.Name = "urlEntry1";
			this.urlEntry1.IsEditable = true;
			this.urlEntry1.InvisibleChar = '●';
			this.hbox21.Add(this.urlEntry1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.urlEntry1]));
			w3.Position = 1;
			// Container child hbox21.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar32\'><toolitem name=\'goButton1\' action=\'goButton1\'/><too" +
					"litem name=\'deleteButton1\' action=\'deleteButton1\'/></toolbar></ui>");
			this.toolbar32 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar32")));
			this.toolbar32.Name = "toolbar32";
			this.toolbar32.ShowArrow = false;
			this.hbox21.Add(this.toolbar32);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.toolbar32]));
			w4.Position = 2;
			this.vbox9.Add(this.hbox21);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox21]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.nameEntry2 = new global::Gtk.Entry();
			this.nameEntry2.Sensitive = false;
			this.nameEntry2.CanFocus = true;
			this.nameEntry2.Name = "nameEntry2";
			this.nameEntry2.IsEditable = true;
			this.nameEntry2.InvisibleChar = '●';
			this.hbox23.Add(this.nameEntry2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.nameEntry2]));
			w6.Position = 0;
			// Container child hbox23.Gtk.Box+BoxChild
			this.urlEntry2 = new global::Gtk.Entry();
			this.urlEntry2.Sensitive = false;
			this.urlEntry2.CanFocus = true;
			this.urlEntry2.Name = "urlEntry2";
			this.urlEntry2.IsEditable = true;
			this.urlEntry2.InvisibleChar = '●';
			this.hbox23.Add(this.urlEntry2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.urlEntry2]));
			w7.Position = 1;
			// Container child hbox23.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar34\'><toolitem name=\'goButton2\' action=\'goButton2\'/><too" +
					"litem name=\'deleteButton2\' action=\'deleteButton2\'/></toolbar></ui>");
			this.toolbar34 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar34")));
			this.toolbar34.Name = "toolbar34";
			this.toolbar34.ShowArrow = false;
			this.hbox23.Add(this.toolbar34);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.toolbar34]));
			w8.Position = 2;
			this.vbox9.Add(this.hbox23);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox23]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.nameEntry3 = new global::Gtk.Entry();
			this.nameEntry3.Sensitive = false;
			this.nameEntry3.CanFocus = true;
			this.nameEntry3.Name = "nameEntry3";
			this.nameEntry3.IsEditable = true;
			this.nameEntry3.InvisibleChar = '●';
			this.hbox25.Add(this.nameEntry3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.nameEntry3]));
			w10.Position = 0;
			// Container child hbox25.Gtk.Box+BoxChild
			this.urlEntry3 = new global::Gtk.Entry();
			this.urlEntry3.Sensitive = false;
			this.urlEntry3.CanFocus = true;
			this.urlEntry3.Name = "urlEntry3";
			this.urlEntry3.IsEditable = true;
			this.urlEntry3.InvisibleChar = '●';
			this.hbox25.Add(this.urlEntry3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.urlEntry3]));
			w11.Position = 1;
			// Container child hbox25.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar36\'><toolitem name=\'goButton3\' action=\'goButton3\'/><too" +
					"litem name=\'deleteButton3\' action=\'deleteButton3\'/></toolbar></ui>");
			this.toolbar36 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar36")));
			this.toolbar36.Name = "toolbar36";
			this.toolbar36.ShowArrow = false;
			this.hbox25.Add(this.toolbar36);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.toolbar36]));
			w12.Position = 2;
			this.vbox9.Add(this.hbox25);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox25]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox8.Add(this.vbox9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.nameEntry4 = new global::Gtk.Entry();
			this.nameEntry4.Sensitive = false;
			this.nameEntry4.CanFocus = true;
			this.nameEntry4.Name = "nameEntry4";
			this.nameEntry4.IsEditable = true;
			this.nameEntry4.InvisibleChar = '●';
			this.hbox27.Add(this.nameEntry4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.nameEntry4]));
			w15.Position = 0;
			// Container child hbox27.Gtk.Box+BoxChild
			this.urlEntry4 = new global::Gtk.Entry();
			this.urlEntry4.Sensitive = false;
			this.urlEntry4.CanFocus = true;
			this.urlEntry4.Name = "urlEntry4";
			this.urlEntry4.IsEditable = true;
			this.urlEntry4.InvisibleChar = '●';
			this.hbox27.Add(this.urlEntry4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.urlEntry4]));
			w16.Position = 1;
			// Container child hbox27.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar38\'><toolitem name=\'goButton4\' action=\'goButton4\'/><too" +
					"litem name=\'deleteButton4\' action=\'deleteButton4\'/></toolbar></ui>");
			this.toolbar38 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar38")));
			this.toolbar38.Name = "toolbar38";
			this.toolbar38.ShowArrow = false;
			this.hbox27.Add(this.toolbar38);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.toolbar38]));
			w17.Position = 2;
			this.vbox11.Add(this.hbox27);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox27]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.nameEntry5 = new global::Gtk.Entry();
			this.nameEntry5.Sensitive = false;
			this.nameEntry5.CanFocus = true;
			this.nameEntry5.Name = "nameEntry5";
			this.nameEntry5.IsEditable = true;
			this.nameEntry5.InvisibleChar = '●';
			this.hbox29.Add(this.nameEntry5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.nameEntry5]));
			w19.Position = 0;
			// Container child hbox29.Gtk.Box+BoxChild
			this.urlEntry5 = new global::Gtk.Entry();
			this.urlEntry5.Sensitive = false;
			this.urlEntry5.CanFocus = true;
			this.urlEntry5.Name = "urlEntry5";
			this.urlEntry5.IsEditable = true;
			this.urlEntry5.InvisibleChar = '●';
			this.hbox29.Add(this.urlEntry5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.urlEntry5]));
			w20.Position = 1;
			// Container child hbox29.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar40\'><toolitem name=\'goButton5\' action=\'goButton5\'/><too" +
					"litem name=\'deleteButton5\' action=\'deleteButton5\'/></toolbar></ui>");
			this.toolbar40 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar40")));
			this.toolbar40.Name = "toolbar40";
			this.toolbar40.ShowArrow = false;
			this.hbox29.Add(this.toolbar40);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.toolbar40]));
			w21.Position = 2;
			this.vbox11.Add(this.hbox29);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox29]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.nameEntry6 = new global::Gtk.Entry();
			this.nameEntry6.Sensitive = false;
			this.nameEntry6.CanFocus = true;
			this.nameEntry6.Name = "nameEntry6";
			this.nameEntry6.IsEditable = true;
			this.nameEntry6.InvisibleChar = '●';
			this.hbox31.Add(this.nameEntry6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.nameEntry6]));
			w23.Position = 0;
			// Container child hbox31.Gtk.Box+BoxChild
			this.urlEntry6 = new global::Gtk.Entry();
			this.urlEntry6.Sensitive = false;
			this.urlEntry6.CanFocus = true;
			this.urlEntry6.Name = "urlEntry6";
			this.urlEntry6.IsEditable = true;
			this.urlEntry6.InvisibleChar = '●';
			this.hbox31.Add(this.urlEntry6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.urlEntry6]));
			w24.Position = 1;
			// Container child hbox31.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar42\'><toolitem name=\'goButton6\' action=\'goButton6\'/><too" +
					"litem name=\'deleteButton6\' action=\'deleteButton6\'/></toolbar></ui>");
			this.toolbar42 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar42")));
			this.toolbar42.Name = "toolbar42";
			this.toolbar42.ShowArrow = false;
			this.hbox31.Add(this.toolbar42);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.toolbar42]));
			w25.Position = 2;
			this.vbox11.Add(this.hbox31);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox31]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox8.Add(this.vbox11);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox11]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.nameEntry7 = new global::Gtk.Entry();
			this.nameEntry7.Sensitive = false;
			this.nameEntry7.CanFocus = true;
			this.nameEntry7.Name = "nameEntry7";
			this.nameEntry7.IsEditable = true;
			this.nameEntry7.InvisibleChar = '●';
			this.hbox33.Add(this.nameEntry7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.nameEntry7]));
			w28.Position = 0;
			// Container child hbox33.Gtk.Box+BoxChild
			this.urlEntry7 = new global::Gtk.Entry();
			this.urlEntry7.Sensitive = false;
			this.urlEntry7.CanFocus = true;
			this.urlEntry7.Name = "urlEntry7";
			this.urlEntry7.IsEditable = true;
			this.urlEntry7.InvisibleChar = '●';
			this.hbox33.Add(this.urlEntry7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.urlEntry7]));
			w29.Position = 1;
			// Container child hbox33.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar44\'><toolitem name=\'goButton7\' action=\'goButton7\'/><too" +
					"litem name=\'deleteButton7\' action=\'deleteButton7\'/></toolbar></ui>");
			this.toolbar44 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar44")));
			this.toolbar44.Name = "toolbar44";
			this.toolbar44.ShowArrow = false;
			this.hbox33.Add(this.toolbar44);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.toolbar44]));
			w30.Position = 2;
			this.vbox13.Add(this.hbox33);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox33]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox35 = new global::Gtk.HBox();
			this.hbox35.Name = "hbox35";
			this.hbox35.Spacing = 6;
			// Container child hbox35.Gtk.Box+BoxChild
			this.nameEntry8 = new global::Gtk.Entry();
			this.nameEntry8.Sensitive = false;
			this.nameEntry8.CanFocus = true;
			this.nameEntry8.Name = "nameEntry8";
			this.nameEntry8.IsEditable = true;
			this.nameEntry8.InvisibleChar = '●';
			this.hbox35.Add(this.nameEntry8);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.nameEntry8]));
			w32.Position = 0;
			// Container child hbox35.Gtk.Box+BoxChild
			this.urlEntry8 = new global::Gtk.Entry();
			this.urlEntry8.Sensitive = false;
			this.urlEntry8.CanFocus = true;
			this.urlEntry8.Name = "urlEntry8";
			this.urlEntry8.IsEditable = true;
			this.urlEntry8.InvisibleChar = '●';
			this.hbox35.Add(this.urlEntry8);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.urlEntry8]));
			w33.Position = 1;
			// Container child hbox35.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar46\'><toolitem name=\'goButton8\' action=\'goButton8\'/><too" +
					"litem name=\'deleteButton8\' action=\'deleteButton8\'/></toolbar></ui>");
			this.toolbar46 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar46")));
			this.toolbar46.Name = "toolbar46";
			this.toolbar46.ShowArrow = false;
			this.hbox35.Add(this.toolbar46);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.toolbar46]));
			w34.Position = 2;
			this.vbox13.Add(this.hbox35);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox35]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox37 = new global::Gtk.HBox();
			this.hbox37.Name = "hbox37";
			this.hbox37.Spacing = 6;
			// Container child hbox37.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.hbox37.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.hseparator1]));
			w36.Position = 0;
			// Container child hbox37.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar30\'><toolitem name=\'editButton\' action=\'editButton\'/><t" +
					"oolitem name=\'saveButton\' action=\'saveButton\'/></toolbar></ui>");
			this.toolbar30 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar30")));
			this.toolbar30.Name = "toolbar30";
			this.toolbar30.ShowArrow = false;
			this.hbox37.Add(this.toolbar30);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.toolbar30]));
			w37.Position = 1;
			// Container child hbox37.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.hbox37.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.hseparator3]));
			w38.Position = 2;
			this.vbox13.Add(this.hbox37);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox37]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox8.Add(this.vbox13);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox13]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.Add(this.vbox8);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 492;
			this.DefaultHeight = 405;
			this.Show();
			this.editButton.Activated += new global::System.EventHandler(this.EditButtonClicked);
			this.saveButton.Activated += new global::System.EventHandler(this.SaveButtonClicked);
			this.goButton1.Activated += new global::System.EventHandler(this.GoButton1Clicked);
			this.deleteButton1.Activated += new global::System.EventHandler(this.DeleteButton1Clicked);
			this.goButton2.Activated += new global::System.EventHandler(this.GoButton2Clicked);
			this.deleteButton2.Activated += new global::System.EventHandler(this.DeleteButton2Clicked);
			this.goButton3.Activated += new global::System.EventHandler(this.GoButton3Clicked);
			this.deleteButton3.Activated += new global::System.EventHandler(this.DeleteButton3Clicked);
			this.goButton4.Activated += new global::System.EventHandler(this.GoButton4Clicked);
			this.deleteButton4.Activated += new global::System.EventHandler(this.DeleteButton4Clicked);
			this.goButton5.Activated += new global::System.EventHandler(this.GoButton5Clicked);
			this.deleteButton5.Activated += new global::System.EventHandler(this.DeleteButton5Clicked);
			this.goButton6.Activated += new global::System.EventHandler(this.GoButton6Clicked);
			this.deleteButton6.Activated += new global::System.EventHandler(this.DeleteButton6Clicked);
			this.goButton7.Activated += new global::System.EventHandler(this.GoButton7Clicked);
			this.deleteButton7.Activated += new global::System.EventHandler(this.DeleteButton7Clicked);
			this.goButton8.Activated += new global::System.EventHandler(this.GoButton8Clicked);
			this.deleteButton8.Activated += new global::System.EventHandler(this.DeleteButton8Clicked);
		}
	}
}
