
// This file has been generated by the GUI designer. Do not modify.
namespace MiniBowserGUI
{
	public partial class HistWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action goButton1;

		private global::Gtk.Action goButton2;

		private global::Gtk.Action goButton3;

		private global::Gtk.Action goButton4;

		private global::Gtk.Action goButton5;

		private global::Gtk.Action goButton6;

		private global::Gtk.Action goButton7;

		private global::Gtk.Action goButton8;

		private global::Gtk.Action clearHistoryButton;

		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry urlEntry1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Entry urlEntry2;

		private global::Gtk.Toolbar toolbar3;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Entry urlEntry3;

		private global::Gtk.Toolbar toolbar5;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Entry urlEntry4;

		private global::Gtk.Toolbar toolbar7;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Entry urlEntry5;

		private global::Gtk.Toolbar toolbar9;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Entry urlEntry6;

		private global::Gtk.Toolbar toolbar11;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Entry urlEntry7;

		private global::Gtk.Toolbar toolbar13;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Entry urlEntry8;

		private global::Gtk.Toolbar toolbar15;

		private global::Gtk.HBox hbox11;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Toolbar toolbar17;

		private global::Gtk.HSeparator hseparator1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MiniBowserGUI.HistWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.goButton1 = new global::Gtk.Action("goButton1", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton1.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton1, null);
			this.goButton2 = new global::Gtk.Action("goButton2", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton2.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton2, null);
			this.goButton3 = new global::Gtk.Action("goButton3", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton3.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton3, null);
			this.goButton4 = new global::Gtk.Action("goButton4", null, null, "gtk-find");
			w1.Add(this.goButton4, null);
			this.goButton5 = new global::Gtk.Action("goButton5", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton5.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton5, null);
			this.goButton6 = new global::Gtk.Action("goButton6", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton6.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton6, null);
			this.goButton7 = new global::Gtk.Action("goButton7", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton7.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton7, null);
			this.goButton8 = new global::Gtk.Action("goButton8", global::Mono.Unix.Catalog.GetString("Go"), null, "gtk-find");
			this.goButton8.ShortLabel = global::Mono.Unix.Catalog.GetString("Go");
			w1.Add(this.goButton8, null);
			this.clearHistoryButton = new global::Gtk.Action("clearHistoryButton", global::Mono.Unix.Catalog.GetString("Clear History"), null, "gtk-stop");
			this.clearHistoryButton.ShortLabel = global::Mono.Unix.Catalog.GetString("Clear History");
			w1.Add(this.clearHistoryButton, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "MiniBowserGUI.HistWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("HistWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MiniBowserGUI.HistWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.urlEntry1 = new global::Gtk.Entry();
			this.urlEntry1.Sensitive = false;
			this.urlEntry1.CanFocus = true;
			this.urlEntry1.Name = "urlEntry1";
			this.urlEntry1.IsEditable = true;
			this.urlEntry1.InvisibleChar = '●';
			this.hbox1.Add(this.urlEntry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.urlEntry1]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'goButton1\' action=\'goButton1\'/></too" +
					"lbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.hbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.toolbar1]));
			w3.Position = 1;
			this.vbox6.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.urlEntry2 = new global::Gtk.Entry();
			this.urlEntry2.Sensitive = false;
			this.urlEntry2.CanFocus = true;
			this.urlEntry2.Name = "urlEntry2";
			this.urlEntry2.IsEditable = true;
			this.urlEntry2.InvisibleChar = '●';
			this.hbox3.Add(this.urlEntry2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.urlEntry2]));
			w5.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar3\'><toolitem name=\'goButton2\' action=\'goButton2\'/></too" +
					"lbar></ui>");
			this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
			this.toolbar3.Name = "toolbar3";
			this.toolbar3.ShowArrow = false;
			this.hbox3.Add(this.toolbar3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.toolbar3]));
			w6.Position = 1;
			this.vbox6.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox3]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.urlEntry3 = new global::Gtk.Entry();
			this.urlEntry3.Sensitive = false;
			this.urlEntry3.CanFocus = true;
			this.urlEntry3.Name = "urlEntry3";
			this.urlEntry3.IsEditable = true;
			this.urlEntry3.InvisibleChar = '●';
			this.hbox5.Add(this.urlEntry3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.urlEntry3]));
			w8.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar5\'><toolitem name=\'goButton3\' action=\'goButton3\'/></too" +
					"lbar></ui>");
			this.toolbar5 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar5")));
			this.toolbar5.Name = "toolbar5";
			this.toolbar5.ShowArrow = false;
			this.hbox5.Add(this.toolbar5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.toolbar5]));
			w9.Position = 1;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add(this.vbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox6]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.urlEntry4 = new global::Gtk.Entry();
			this.urlEntry4.Sensitive = false;
			this.urlEntry4.CanFocus = true;
			this.urlEntry4.Name = "urlEntry4";
			this.urlEntry4.IsEditable = true;
			this.urlEntry4.InvisibleChar = '●';
			this.hbox7.Add(this.urlEntry4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.urlEntry4]));
			w12.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar7\'><toolitem name=\'goButton4\' action=\'goButton4\'/></too" +
					"lbar></ui>");
			this.toolbar7 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar7")));
			this.toolbar7.Name = "toolbar7";
			this.toolbar7.ShowArrow = false;
			this.hbox7.Add(this.toolbar7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.toolbar7]));
			w13.Position = 1;
			this.vbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.urlEntry5 = new global::Gtk.Entry();
			this.urlEntry5.Sensitive = false;
			this.urlEntry5.CanFocus = true;
			this.urlEntry5.Name = "urlEntry5";
			this.urlEntry5.IsEditable = true;
			this.urlEntry5.InvisibleChar = '●';
			this.hbox9.Add(this.urlEntry5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.urlEntry5]));
			w15.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar9\'><toolitem name=\'goButton5\' action=\'goButton5\'/></too" +
					"lbar></ui>");
			this.toolbar9 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar9")));
			this.toolbar9.Name = "toolbar9";
			this.toolbar9.ShowArrow = false;
			this.hbox9.Add(this.toolbar9);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.toolbar9]));
			w16.Position = 1;
			this.vbox4.Add(this.hbox9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox9]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.urlEntry6 = new global::Gtk.Entry();
			this.urlEntry6.Sensitive = false;
			this.urlEntry6.CanFocus = true;
			this.urlEntry6.Name = "urlEntry6";
			this.urlEntry6.IsEditable = true;
			this.urlEntry6.InvisibleChar = '●';
			this.hbox17.Add(this.urlEntry6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.urlEntry6]));
			w18.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar11\'><toolitem name=\'goButton6\' action=\'goButton6\'/></to" +
					"olbar></ui>");
			this.toolbar11 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar11")));
			this.toolbar11.Name = "toolbar11";
			this.toolbar11.ShowArrow = false;
			this.hbox17.Add(this.toolbar11);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.toolbar11]));
			w19.Position = 1;
			this.vbox4.Add(this.hbox17);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox17]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.urlEntry7 = new global::Gtk.Entry();
			this.urlEntry7.Sensitive = false;
			this.urlEntry7.CanFocus = true;
			this.urlEntry7.Name = "urlEntry7";
			this.urlEntry7.IsEditable = true;
			this.urlEntry7.InvisibleChar = '●';
			this.hbox15.Add(this.urlEntry7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.urlEntry7]));
			w22.Position = 0;
			// Container child hbox15.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar13\'><toolitem name=\'goButton7\' action=\'goButton7\'/></to" +
					"olbar></ui>");
			this.toolbar13 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar13")));
			this.toolbar13.Name = "toolbar13";
			this.toolbar13.ShowArrow = false;
			this.hbox15.Add(this.toolbar13);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.toolbar13]));
			w23.Position = 1;
			this.vbox2.Add(this.hbox15);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox15]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.urlEntry8 = new global::Gtk.Entry();
			this.urlEntry8.Sensitive = false;
			this.urlEntry8.CanFocus = true;
			this.urlEntry8.Name = "urlEntry8";
			this.urlEntry8.IsEditable = true;
			this.urlEntry8.InvisibleChar = '●';
			this.hbox13.Add(this.urlEntry8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.urlEntry8]));
			w25.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar15\'><toolitem name=\'goButton8\' action=\'goButton8\'/></to" +
					"olbar></ui>");
			this.toolbar15 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar15")));
			this.toolbar15.Name = "toolbar15";
			this.toolbar15.ShowArrow = false;
			this.hbox13.Add(this.toolbar15);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.toolbar15]));
			w26.Position = 1;
			this.vbox2.Add(this.hbox13);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox13]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.hbox11.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hseparator3]));
			w28.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar17\'><toolitem name=\'clearHistoryButton\' action=\'clearHi" +
					"storyButton\'/></toolbar></ui>");
			this.toolbar17 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar17")));
			this.toolbar17.Name = "toolbar17";
			this.toolbar17.ShowArrow = false;
			this.hbox11.Add(this.toolbar17);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.toolbar17]));
			w29.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.hbox11.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hseparator1]));
			w30.Position = 2;
			this.vbox2.Add(this.hbox11);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox11]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 390;
			this.Show();
			this.goButton1.Activated += new global::System.EventHandler(this.GoButton1Clicked);
			this.goButton2.Activated += new global::System.EventHandler(this.GoButton2Clicked);
			this.goButton3.Activated += new global::System.EventHandler(this.GoButton3Clicked);
			this.goButton4.Activated += new global::System.EventHandler(this.GoButton4Clicked);
			this.goButton5.Activated += new global::System.EventHandler(this.GoButton5Clicked);
			this.goButton6.Activated += new global::System.EventHandler(this.GoButton6Clicked);
			this.goButton7.Activated += new global::System.EventHandler(this.GoButton7Clicked);
			this.goButton8.Activated += new global::System.EventHandler(this.GoButton8Clicked);
			this.clearHistoryButton.Activated += new global::System.EventHandler(this.ClearHistoryButtonClicked);
		}
	}
}
